### ISSUE TITLE
Any update of data in ZCTA.csv?

### ISSUE THREAD

**Issue by ILOFI** [thecityny/covid-19-nyc-data#4]
The last update on ZCTA.csv was a month ago, would you please update it to a more recently one?

**Comment by willcwelch** [comment]
As of May 19 we are no longer updating `borough.csv`, `age.csv`, `gender.csv`, `nyc.csv` and `zcta.csv`. You can find the data for ZCTA.csv here: https://github.com/nychealth/coronavirus-data/blob/master/data-by-modzcta.csv.
